Написать функцию вычисления факториала
js-tasks-ru/jsbasic-20211108_sabbat pull request #2
Opened 2021-11-11 09:03 UTC by Kirill-Malskiy

2021-11-11 09:04 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-11 10:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-11-11 10:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-11-11 10:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-11-11 12:50 UTC, SinimaWath requested changes

2021-11-11 12:50 UTC, SinimaWath commented on 1-module/3-task/index.js
> +    return newStr;
Тут можно без временной переменной newStr - давай сразу вернем результат операции

2021-11-11 12:50 UTC, SinimaWath commented on 1-module/5-task/index.js
> +        str = str.slice(0, maxlength - 1) + '…';
Присваивание значений аргументам функций, это считается антипаттерном - плохим, тоном. Который может привести к неявным багам.

Лучше создать новую переменную

2021-11-11 16:01 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-12 10:51 UTC, SinimaWath requested changes

2021-11-12 10:51 UTC, SinimaWath commented on 1-module/3-task/index.js
> +    return str = str.charAt(0).toUpperCase() + str.slice(1);
Присваивание тут лишнее, непонятно зачем оно нужно, если переменную не используешь:
`return str.charAt(0).toUpperCase() + str.slice(1)`

2021-11-12 10:51 UTC, SinimaWath commented on 1-module/5-task/index.js
> +        str = str.slice(0, strSlice - 1) + '…';
Тут тоже присваивание лишнее, можно сразу вернуть результат в return;

`return str.slice(0, strSlice - 1) + '…'`

2021-11-12 11:01 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-12 15:51 UTC, SinimaWath approved these changes

2021-11-12 15:52 UTC, merged